{ config, pkgs, inputs, username, host, ... }:

{
  imports = [
    # Include the hardware configuration generated by nixos-generate-config
    ./hardware-configuration.nix

    # Shared common configuration
    ./../../modules/nixos
    ./disko-config.nix
  ];

  services.nfsClient.enable = true;
  # Boot configuration
  boot = {
    kernelModules = [ "acpi_call" "tp_smapi" ];
    extraModulePackages = with config.boot.kernelPackages; [ acpi_call tp_smapi ];
    kernelParams = [
      "mem_sleep_default=deep" # Better sleep state
      "nvme.noacpi=1"         # Fix potential NVMe issues
    ];

    loader = {
      systemd-boot.enable = true;
      efi.canTouchEfiVariables = true;
      timeout = 3;
    };
  };

  # Hardware specific settings
  hardware = {
    # Enable T480-specific power management
    cpu.intel.updateMicrocode = true;
    opengl = {
      enable = true;
      extraPackages = with pkgs; [
        intel-media-driver
        intel-vaapi-driver # previously vaapiIntel
        vaapiVdpau
        libvdpau-va-gl
        intel-compute-runtime # OpenCL filter support (hardware tonemapping and subtitle burn-in)
        intel-media-sdk # QSV up to 11th gen
      ];
    };
  };

  # Power management
  powerManagement = {
    enable = true;
    powertop.enable = true;
    cpuFreqGovernor = "performance";
  };

  services = {
    # Thermal management
    thermald.enable = true;

    # Enable fingerprint
    fprintd.enable = true;

    # Enable ThinkPad specific services
    tlp = {
      enable = true;
      settings = {
        CPU_SCALING_GOVERNOR_ON_AC = "performance";
        CPU_SCALING_GOVERNOR_ON_BAT = "performance";
        CPU_ENERGY_PERF_POLICY_ON_BAT = "performance";
        CPU_ENERGY_PERF_POLICY_ON_AC = "performance";
        START_CHARGE_THRESH_BAT0 = 80;
        STOP_CHARGE_THRESH_BAT0 = 90;
      };
    };

    # Throttling prevention
    undervolt = {
      enable = true;
      coreOffset = -100;
      gpuOffset = -80;
      uncoreOffset = -100;
      analogioOffset = 0;
    };

    # Automatic brightness adjustment
    auto-cpufreq = {
      enable = true;
      settings = {
        battery = {
          governor = "performance";
        };
        charger = {
          governor = "performance";
        };
      };
    };
  };

  # System packages
  environment.systemPackages = with pkgs; [
    # Hardware tools
    acpi
    lm_sensors
    powertop
    smartmontools
    tlp

    # ThinkPad utilities
    thinkfan
    throttled
  ];

  # User configuration
  users.users.${username} = {
    extraGroups = [ "video" "audio" "lp" "scanner" ];
  };

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  system.stateVersion = "24.11";
} 
