{ ... }:
{
  wayland.windowManager.hyprland = {
     settings = {
       bind = [
                "bind = $mainMod, Q, killactive"
                "bind = $mainMod, F, fullscreen"
                "bind = $mainMod shift, Space, togglefloating"
                "bind = $mainMod, J, movefocus, l"
                "bind = $mainMod, K, movefocus, r"
                "bind = $mainMod shift, h, movewindow, l"
                "bind = $mainMod shift, j, movewindow, d"
                "bind = $mainMod shift, k, movewindow, u"
                "bind = $mainMod shift, l, movewindow, r"
                "bind = $mainMod, h, resizeactive, -100 0"
                "bind = $mainMod, l, resizeactive, 100 0"
                "bind = $mainMod, Space, swapsplit"
                "bind = $mainMod, s, pin"
                "bindm = $mainMod, mouse:272, movewindow"
                "bindm = $mainMod, mouse:273, resizewindow"
                "bind = $mainMod, a, exec, killall -SIGUSR1 waybar"
                
                "bind = $mainMod, W, exec, zen-browser"
                "bind = $mainMod, E, exec, bemoji -t"
                "bind = $mainMod, R, exec, foot -e yazi"
                "bind = $mainMod, Y, exec, vesktop"
                "bind = $mainMod, U, exec, obs"
                "bind = $mainMod, O, exec, prismlauncher"
                "bind = $mainMod, D, exec, fuzzel"
                "bind = $mainMod, backspace, exec, hyprlock"
                "bind = $mainMod shift, C, exec, hyprpicker -a"
                "bind = $mainMod, V, exec, cliphist list | fuzzel --match-mode fzf --dmenu | cliphist decode | wl-copy"
                "bind = $mainMod shift, V, exec, foot -e cava"
                "bind = $mainMod, N, exec, flatpak run com.valvesoftware.Steam"
                "bind = $mainMod, M, exec, foot -e ncmpcpp"
                "bind = $mainMod, Return, exec, foot"
                "bind = , Print, exec, grimblast --freeze copysave area $shot"
                "bind = Ctrl, Print, exec, grimblast --freeze save area - | swappy -f -"
                "bind = SHIFT, Print, exec, grimblast copysave output $shot"
                "bind = Ctrl SHIFT, Print, exec, grimblast --freeze save output - | swappy -f -"
                "bind = $mainMod, Print, exec, grimblast --freeze copysave active $shot"
                "bind = $mainMod Ctrl, Print, exec, grimblast --freeze save active - | swappy -f -"
                
                "bindl  = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"
                "bindle = , XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"
                "bindle = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"
                "bindl  = , XF86AudioNext, exec, playerctl next"
                "bindl  = , XF86AudioPrev, exec, playerctl previous"
                "bindl  = , XF86AudioPlay, exec, playerctl play-pause"
                "bindl  = , XF86AudioPause, exec, playerctl previous"
                "bindle = , XF86MonBrightnessUp, exec, brightnessctl set '+5%'"
                "bindle = , XF86MonBrightnessDown, exec, brightnessctl set '5%-'"
                
                "bind = $mainMod, 1, split-workspace, 1"
                "bind = $mainMod, 2, split-workspace, 2"
                "bind = $mainMod, 3, split-workspace, 3"
                "bind = $mainMod, 4, split-workspace, 4"
                "bind = $mainMod, 5, split-workspace, 5"
                "bind = $mainMod, 6, split-workspace, 6"
                "bind = $mainMod, 7, split-workspace, 7"
                "bind = $mainMod, 8, split-workspace, 8"
                "bind = $mainMod, 9, split-workspace, 9"
                "bind = $mainMod, 0, split-workspace, 10"
                
                "bind = $mainMod SHIFT, 1, split-movetoworkspace, 1"
                "bind = $mainMod SHIFT, 2, split-movetoworkspace, 2"
                "bind = $mainMod SHIFT, 3, split-movetoworkspace, 3"
                "bind = $mainMod SHIFT, 4, split-movetoworkspace, 4"
                "bind = $mainMod SHIFT, 5, split-movetoworkspace, 5"
                "bind = $mainMod SHIFT, 6, split-movetoworkspace, 6"
                "bind = $mainMod SHIFT, 7, split-movetoworkspace, 7"
                "bind = $mainMod SHIFT, 8, split-movetoworkspace, 8"
                "bind = $mainMod SHIFT, 9, split-movetoworkspace, 9"
                "bind = $mainMod SHIFT, 0, split-movetoworkspace, 10"
       ];
     };
  };
}
